version: '3.9'

services:
  authen-service:
    restart: always
    container_name: authen-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:5001:5001
    volumes:
      - .:/authen_service