version: '3.9'

services:
  authen-service:
    restart: always
    container_name: authen-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - .:/authen_service