version: '4.0'

services:
  authen-service:
    restart: always
    container_name: apigateway
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - .:/apigateway